# Generated by Django 3.0.7 on 2021-06-12 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('content', models.TextField(max_length=1000)),
                ('image', models.ImageField(blank=True, upload_to='blog/images/')),
            ],
        ),
    ]
